# Generated by Django 2.0.3 on 2018-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True, null='True')),
                ('Full_Names', models.CharField(blank='True', max_length=300, null='True')),
                ('Email', models.CharField(blank='True', max_length=300, null='True')),
                ('Phone', models.CharField(blank='True', max_length=300, null='True')),
                ('Subject', models.CharField(blank='True', max_length=300, null='True')),
                ('Message', models.CharField(blank='True', max_length=300, null='True')),
            ],
        ),
    ]
