# Generated by Django 2.0.3 on 2018-04-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Full_Names',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Phone',
            new_name='Phone_Number',
        ),
    ]
