# Generated by Django 2.0.3 on 2018-04-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180426_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Subject',
            new_name='Estimated_budget',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Tell_Us_About_Your_Project',
            field=models.CharField(blank='True', max_length=300, null='True'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Type_of_Project',
            field=models.CharField(blank='True', max_length=300, null='True'),
        ),
    ]
