# Generated by Django 2.0.3 on 2018-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180426_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Full_Name',
            field=models.CharField(blank='False', max_length=300, null='False'),
        ),
    ]
